export enum OrderStatus {
  PENDING = "PENDING",
  CONFIRMED = "CONFIRMED",
  SENT_LINK = "SENT_LINK",
  PAID = "PAID",
  PURCHASED = "PURCHASED",
  ARRIVED_TW = "ARRIVED_TW",
  SHIPPED = "SHIPPED",
  COMPLETED = "COMPLETED",
  OUT_OF_STOCK = "OUT_OF_STOCK",
  CANCELLED = "CANCELLED"
}

export enum Role {
  ADMIN = "ADMIN",
  CUSTOMER = "CUSTOMER"
}
